---
resources:
  - name: azure_to_jfrog
    type: git
    source:
      uri: https://github.com/jiege3324/acrsync.git
      branch: master
      username: "jiege3324"
      password: "jie1206538127"
jobs:
  - name: start-image-syncer
    serial: true
    plan:
      - get: azure_to_jfrog
      - task: start-image-syncer
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:  {repository: centos}
          inputs:
            - name: azure_to_jfrog
          run:
            path: ./image-syncer.sh
  - name: start-chart-syncer
    serial: true
    plan:
      - get: azure_to_jfrog
      - task: start-chart-syncer
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:  {repository: jingfanghua/image-sync}
          inputs:
            - name: azure_to_jfrog
          run:
            path: ./chart_sync.sh
